---
- hosts: all
  sudo: yes

  tasks:
    - name: Update cache
      apt: 
        update_cache: yes

    - name: Set hostname
      hostname: name={{ inventory_hostname }}
      when: not inventory_hostname is match('(\d{1,3}\.){3}\d{1,3}')

    - name: Ensure hostname is in /etc/hosts
      lineinfile:
        dest=/etc/hosts
        regexp="^{{ ansible_default_ipv4.address }}.+$"
        line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"

    - name: Generate /etc/hosts file
      template:
        src: ../templates/hosts.j2
        dest: /etc/hosts

